import './globals.css'
import { EffectorNext } from '@effector/next'
import { ColorSchemeScript, mantineHtmlProps, MantineProvider } from '@mantine/core'
import type { Metadata } from 'next'

import '@mantine/core/styles.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ru' {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <EffectorNext>
          <MantineProvider>{children}</MantineProvider>
        </EffectorNext>
      </body>
    </html>
  )
}
